version: '3'
services:
    webapp:
        image: scoresite
        ports:
          - "80:80"
        volumes:
          - /Users/bradleyclarke/Documents/Team_Day/score_site/:/usr/share/nginx/html
    api:
        image: teamday
        ports:
            - "8080:8080"
        environment:
            - MONGO_HOST=mongodb
            - MONGO_PORT=27017
#        volumes:
#            - .:/app
    mongodb:
        image: mongo:3.4